///////////////////////////////////////////////////////////
//  DungeonMaster.cs
//  Implementation of the Class DungeonMaster
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2014 10:13:36 PM
//  Original author: Gsimmons
///////////////////////////////////////////////////////////


using System;
using Mazegame.Boundary;
using Mazegame.Entity;
using System.Collections;

namespace Mazegame.Control
{
    public class DungeonMaster
    {
        public IMazeClient gameClient;
        public IMazeData gameData;
        public Player thePlayer;
        //private Parser theParser;
        //private ArrayList commands;
        private CommandHandler playerTurnHandler;

        public DungeonMaster()
        {
            this.gameData = GameFactory.GetInstance().getTheData();
            this.gameClient = GameFactory.GetInstance().getTheClient();
            playerTurnHandler = new CommandHandler();

        }

        public void PrintWelcome()
        {
            gameClient.PlayerMessage(gameData.GetWelcomeMessage());
        }

        public void SetupPlayer()
        {
            String playerName = gameClient.GetReply("What name do you choose to be known by?");
            thePlayer = new Player(playerName, 100);
            thePlayer.getMoney().Add(50);
            thePlayer.setCurrentLocation(gameData.GetStartingLocation());
            
            gameClient.PlayerMessage("Welcome " + playerName + "\n\n");
            gameClient.PlayerMessage("Life Points: " + thePlayer.LifePoints + "\n");
            gameClient.PlayerMessage("Your max weight: " + thePlayer.GetInventory().getStrength() + "kg" + "\n");
            gameClient.PlayerMessage("Total weight of the item: " + thePlayer.GetInventory().GetWeight() + "kg" + "\n");
            gameClient.PlayerMessage("Your money: " + thePlayer.getMoney().getMoney() + " gold pieces"+ "\n\n");
            gameClient.PlayerMessage("You find yourself looking at ");
            gameClient.PlayerMessage(thePlayer.getCurrentLocation().ToString());    
        }

        public void RunGame()
        {
            PrintWelcome();
            SetupPlayer();
            while (handlePlayerTurn())
            {
                
            }
            gameClient.GetReply("\n\n<<Hit enter to exit");
        }

        private bool handlePlayerTurn()
        {
            CommandResponse playerResponse = playerTurnHandler.processTurn(gameClient.getCommand(), thePlayer);
            gameClient.PlayerMessage(playerResponse.getMessage());
            return !playerResponse.getQuitFlag();
        }

    } //end DungeonMaster
} //end namespace Control