///////////////////////////////////////////////////////////
//  Shop.cs
//  Implementation of the Class Shop
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2014 10:13:37 PM
//  Original author: Gsimmons
///////////////////////////////////////////////////////////

using System;

namespace Mazegame.Entity
{
    public class Shop : Location
    {

        public Shop()
        {
        }

        public Shop(String description, String label)
            : base(description, label)
        {
        }

    }//end Shop

}//end namespace Entity